name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup default nightly
      - name: Build Rust project
        run: cargo build --verbose
      - name: Run Rust tests
        run: cargo test --verbose

  build-and-test-js:
    runs-on: ubuntu-latest
    needs: build-and-test-rust
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build Wasm package
        run: wasm-pack build --target nodejs --out-dir ../../pkg
        working-directory: crates/chrome-extensions
      - name: Install JavaScript dependencies
        run: npm install
        working-directory: js_tests
      - name: Run Jest tests
        run: npm test
        working-directory: js_tests
